# Generated by Django 5.2.7 on 2026-03-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
