# Generated by Django 5.2.7 on 2026-03-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mods", "0002_fileupload_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
