# Generated by Django 5.2.7 on 2026-03-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mods", "0002_modimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="modimage",
            name="is_cover",
            field=models.BooleanField(default=False),
        ),
    ]
