# Generated by Django 5.2.7 on 2026-03-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mods", "0003_modimage_is_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="mod",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
