# Generated by Django 5.2.7 on 2026-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0003_fileupload_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
