# Generated by Django 5.2.7 on 2026-03-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mods", "0004_alter_fileupload_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="mod",
            name="prlicense",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
