# Generated by Django 5.2.7 on 2026-04-01 07:04

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0004_mod_description'),
        ('shared', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.CreateModel(
            name='ModTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tag')),
            ],
            options={
                'unique_together': {('mod', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='mod',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mods', through='mods.ModTag', to='shared.tag'),
        ),
    ]
