# Generated by Django 5.2.7 on 2026-03-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0006_alter_filegroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filegroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
